name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - OpenAI-DotNet/**
      - OpenAI-DotNet-Proxy/**
  pull_request:
    branches:
      - '*'
    paths:
      - OpenAI-DotNet/**
      - OpenAI-DotNet-Proxy/**
    types:
      - opened
      - synchronize

  workflow_dispatch:
    inputs:
      dotnet-version:
        description: ".NET version to use"
        required: false
        default: "8.0.x"

permissions:
  contents: read
  pages: write
  checks: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  DOTNET_VERSION: ${{ github.event.inputs.dotnet-version || '8.0.x' }}

jobs:
  build:
    if: ${{ !github.event_name == 'pull_request' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore

    - name: Get Version
      id: version
      shell: bash
      run: |
        project_path="${{ github.workspace }}/OpenAI-DotNet/OpenAI-DotNet.csproj"

        if [ ! -f "$project_path" ]; then
          echo "Project file not found at $project_path"
          exit 1
        fi

        version=$(grep -oPm1 '(?<=<Version>)[^<]+' "$project_path" || true)

        if [ -z "$version" ]; then
          echo "Version not found in csproj."
          exit 1
        fi

        echo "Project Version: $version"
        echo "PACKAGE_VERSION=$version" >> "$GITHUB_OUTPUT"

    - name: Test Packages
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' }}
      run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --logger:trx --no-build --no-restore --results-directory ./test-results
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}

    - name: Publish Test Results
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' && always() }}
      uses: EnricoMi/publish-unit-test-result-action@34d7c956a59aed1bfebf31df77b8de55db9bbaaf # v2.11.0
      with:
        files: test-results/**/*.trx
        comment_mode: off
        report_individual_runs: true
        compare_to_earlier_commit: false
        large_files: true

    - name: Determine Coverage File Path
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' && always() }}
      id: coverage-path
      shell: bash
      run: |
        COVERAGE_FILE_PATH=$(find ./test-results -name 'coverage.cobertura.xml' | head -n 1)
        echo "COVERAGE_FILE_PATH=$COVERAGE_FILE_PATH" >> $GITHUB_OUTPUT

    - name: Code Coverage Summary Report
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' && always() }}
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      with:
        filename: ${{ steps.coverage-path.outputs.COVERAGE_FILE_PATH }}
        badge: true
        format: markdown
        output: both

    - name: Write Coverage Job Summary
      if: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' && always() }}
      shell: bash
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Pack and Publish NuGet Package
      run: |
        $projectPath = "${{ github.workspace }}\OpenAI-DotNet"
        $proxyProjectPath = "${{ github.workspace }}\OpenAI-DotNet-Proxy"
        
        # pack OpenAI-DotNet
        dotnet pack $projectPath --configuration Release --include-symbols
        $out = "$projectPath\bin\Release"
        $packagePath = Get-ChildItem -Path $out -File -Include '*.nupkg' -Exclude '*symbols*' -Recurse -ErrorAction SilentlyContinue
        
        if ($packagePath) {
          Write-Host Package path: $packagePath
        } else {
          Write-Host Failed to find package at $out
          exit 1
        }
        
        # pack OpenAI-DotNet-Proxy
        dotnet pack $proxyProjectPath --configuration Release --include-symbols
        $proxyOut = "$proxyProjectPath\bin\Release"
        $proxyPackagePath = Get-ChildItem -Path $proxyOut -File -Include '*.nupkg' -Exclude '*symbols*' -Recurse -ErrorAction SilentlyContinue
        
        if ($proxyPackagePath) {
          Write-Host Package path: $proxyPackagePath
        } else {
          Write-Host Failed to find package at $proxyOut
          exit 1
        }
        
        $isRelease = "${{ github.ref == 'refs/heads/main' }}"
        
        if ($isRelease -eq 'true') {
          dotnet nuget push $packagePath.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push $proxyPackagePath.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        }

    - uses: actions/upload-artifact@v6
      if: always()
      with:
        name: OpenAI-DotNet.${{ steps.version.outputs.PACKAGE_VERSION }}
        path: |
          ${{ github.workspace }}/test-results
          ${{ github.workspace }}/OpenAI-DotNet/bin/Release/OpenAI-DotNet.${{ steps.version.outputs.PACKAGE_VERSION }}.nupkg
          ${{ github.workspace }}/OpenAI-DotNet/bin/Release/OpenAI-DotNet.${{ steps.version.outputs.PACKAGE_VERSION }}.symbols.nupkg
          ${{ github.workspace }}/OpenAI-DotNet/bin/Release/OpenAI-DotNet-Proxy.${{ steps.version.outputs.PACKAGE_VERSION }}.nupkg
          ${{ github.workspace }}/OpenAI-DotNet/bin/Release/OpenAI-DotNet-Proxy.${{ steps.version.outputs.PACKAGE_VERSION }}.symbols.nupkg
        if-no-files-found: ignore

  docs:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: build docfx
      run: |
        dotnet tool update -g docfx
        docfx .docs/docfx.json
    - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: '_site'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
